apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
spec:
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
       - name: shoppingapi
         image: shoppingacr100.azurecr.io/shoppingapi:v1        
         resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.3"
         ports:
          - containerPort: 80
         env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString
            valueFrom:
               configMapKeyRef:
                       name: mongo-configmap
                       key: connection_string
      imagePullSecrets:
          - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:  
  selector:
    app: shoppingapi
  ports:
   - protocol: TCP
     port: 80
    
